version: 0.0.0.{build}
platform: Any CPU
skip_tags: true

assembly_info:
  patch: true
  file: 'DGJv3\Properties\AssemblyInfo.cs'
  assembly_version: $(APPVEYOR_BUILD_VERSION)
  assembly_file_version: $(APPVEYOR_BUILD_VERSION)
  assembly_informational_version: $(APPVEYOR_BUILD_VERSION)


cache:
  - packages

install:
  - ps: ./CI/appveyor_install.ps1

before_build:
  - nuget restore -Verbosity quiet
  - msbuild /nologo /v:q /t:Clean

build_script:
  - ps: msbuild /nologo /v:q /p:Configuration="$env:CONFIGURATION" /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

for:
-
  branches:
    only:
      - master # including pull requests target at master
  configuration: Release
  deploy: # wont run on pull request
    provider: GitHub
    release: v$(APPVEYOR_BUILD_VERSION)
    description: "# 点歌姬 $(APPVEYOR_BUILD_VERSION)\n\nCI 自动发布"
    auth_token:
      secure: F6IbjAMR1BNnH/Q4DYY991sHSUDPSRU8Rh5hLxK1ZEA6cBuousBxwcHUj2iU5dT/
    artifact: DGJv3.dll
    force_update: true
  artifacts:
    - path: DGJv3\bin\Release
      name: DGJv3ReleaseBuild
    - path: DGJv3\bin\Release\x64\DGJv3.dll
      name: DGJv3.dll
-
  configuration: Debug
  artifacts:
    - path: DGJv3\bin\Debug
      name: DGJv3DebugBuild

#on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
